import type { NodeType } from '../src/types'

export const requiredMarkdownFeatures = [
  'empty',
  'atx-heading',
  'setext-heading',
  'thematic-break',
  'paragraph',
  'blank-line',
  'indented-code',
  'fenced-code',
  'html-block',
  'link-definition',
  'blockquote',
  'nested-blockquote',
  'unordered-list',
  'list-markers',
  'ordered-list',
  'list-nesting',
  'list-loose',
  'list-empty',
  'list-continuation',
  'escape',
  'entity',
  'inline-code',
  'emphasis',
  'strong',
  'delete',
  'link',
  'image',
  'inline-html',
  'link-inline-format',
  'autolink',
  'gfm-autolink',
  'raw-html',
  'hard-break',
  'soft-break',
  'table',
  'table-alignment',
  'table-pipe-escape',
  'table-empty-cell',
  'table-column-mismatch',
  'task-list',
  'task-nesting',
  'crlf',
  'cr',
  'tab',
  'unicode',
  'no-trailing-newline',
  'malformed',
  'dangerous-url',
  'composition',
] as const

export type MarkdownFeature = (typeof requiredMarkdownFeatures)[number]

export interface MarkdownFixture {
  id: string
  features: readonly MarkdownFeature[]
  expectedAst: readonly NodeType[]
  source: string
  html: string
}

const tick = String.fromCharCode(96)

export const markdownFixtures: readonly MarkdownFixture[] = [
  {
    id: 'empty-document',
    features: ['empty'],
    expectedAst: [],
    source: '',
    html: '',
  },
  {
    id: 'headings-and-setext',
    features: ['atx-heading', 'setext-heading'],
    expectedAst: ['heading', 'heading'],
    source: '# ATX\n\nSetext\n======',
    html: '<h1>ATX</h1><h1>Setext</h1>',
  },
  {
    id: 'thematic-break-and-paragraph',
    features: ['thematic-break', 'paragraph'],
    expectedAst: ['paragraph', 'thematicBreak', 'paragraph'],
    source: 'before\n\n***\n\nafter',
    html: '<p>before</p><hr><p>after</p>',
  },
  {
    id: 'blank-lines',
    features: ['blank-line'],
    expectedAst: ['paragraph', 'paragraph'],
    source: 'one\n\n\ntwo',
    html: '<p>one</p><p>two</p>',
  },
  {
    id: 'indented-code',
    features: ['indented-code'],
    expectedAst: ['code'],
    source: '    const x = 1',
    html: '<pre><code>const x = 1</code></pre>',
  },
  {
    id: 'fenced-code-with-metadata',
    features: ['fenced-code'],
    expectedAst: ['code'],
    source: '~~~ts extra\nconst x = 1\n~~~',
    html: '<pre><code data-language="ts">const x = 1</code></pre>',
  },
  {
    id: 'unclosed-fenced-code',
    features: ['fenced-code', 'malformed'],
    expectedAst: ['code'],
    source: tick.repeat(3) + 'ts\nconst x = 1',
    html: '<pre><code data-language="ts" data-incomplete="true">const x = 1</code></pre>',
  },
  {
    id: 'html-block-is-safe-by-default',
    features: ['html-block', 'raw-html'],
    expectedAst: ['html'],
    source: '<div>raw</div>',
    html: '&lt;div&gt;raw&lt;/div&gt;',
  },
  {
    id: 'reference-link-and-image',
    features: ['link-definition', 'link', 'image'],
    expectedAst: ['paragraph', 'definition', 'definition'],
    source: '[docs][guide] and ![logo][image]\n\n[guide]: /docs "Guide"\n[image]: /logo.svg',
    html: '<p><a href="/docs" title="Guide">docs</a> and <img src="/logo.svg" alt="logo"></p>',
  },
  {
    id: 'nested-blockquotes',
    features: ['blockquote', 'nested-blockquote'],
    expectedAst: ['blockquote'],
    source: '> outer\n>\n> > inner',
    html: '<blockquote><p>outer</p><blockquote><p>inner</p></blockquote></blockquote>',
  },
  {
    id: 'unordered-list',
    features: ['unordered-list'],
    expectedAst: ['list'],
    source: '- one\n- two',
    html: '<ul><li>one</li><li>two</li></ul>',
  },
  {
    id: 'unordered-list-markers',
    features: ['unordered-list', 'list-markers'],
    expectedAst: ['list', 'list'],
    source: '+ plus\n* star',
    html: '<ul><li>plus</li></ul><ul><li>star</li></ul>',
  },
  {
    id: 'ordered-list-start',
    features: ['ordered-list'],
    expectedAst: ['list'],
    source: '3. three\n4. four',
    html: '<ol start="3"><li>three</li><li>four</li></ol>',
  },
  {
    id: 'nested-list',
    features: ['list-nesting'],
    expectedAst: ['list'],
    source: '- outer\n  - inner\n  - second',
    html: '<ul><li>outer<ul><li>inner</li><li>second</li></ul></li></ul>',
  },
  {
    id: 'loose-list',
    features: ['list-loose'],
    expectedAst: ['list'],
    source: '- one\n\n- two',
    html: '<ul><li><p>one</p></li><li><p>two</p></li></ul>',
  },
  {
    id: 'empty-list-item',
    features: ['list-empty'],
    expectedAst: ['list'],
    source: '-\n- value',
    html: '<ul><li></li><li>value</li></ul>',
  },
  {
    id: 'list-continuation',
    features: ['list-continuation', 'composition'],
    expectedAst: ['list'],
    source: '- first\n  continuation\n\n  ~~~\n  code\n  ~~~',
    html: '<ul><li>first\ncontinuation<pre><code>code</code></pre></li></ul>',
  },
  {
    id: 'escaping-and-entities',
    features: ['escape', 'entity'],
    expectedAst: ['paragraph'],
    source: '\\*literal\\* &amp; &#x41; &copy;',
    html: '<p>*literal* &amp; A ©</p>',
  },
  {
    id: 'inline-code-and-emphasis',
    features: ['inline-code', 'emphasis', 'strong', 'composition'],
    expectedAst: ['paragraph'],
    source: tick + 'a  b' + tick + ' *em* **strong** ***both***',
    html: '<p><code>a  b</code> <em>em</em> <strong>strong</strong> <em><strong>both</strong></em></p>',
  },
  {
    id: 'deletion-and-link',
    features: ['delete', 'link'],
    expectedAst: ['paragraph'],
    source: '~~removed~~ [Markvia](https://example.com "site")',
    html: '<p><del>removed</del> <a href="https://example.com" title="site">Markvia</a></p>',
  },
  {
    id: 'inline-formatted-link-and-image',
    features: ['link-inline-format', 'image'],
    expectedAst: ['paragraph'],
    source:
      '[**bold** and ' +
      tick +
      'code' +
      tick +
      '](https://example.com) ![alt](https://example.com/a.png)',
    html: '<p><a href="https://example.com"><strong>bold</strong> and <code>code</code></a> <img src="https://example.com/a.png" alt="alt"></p>',
  },
  {
    id: 'classic-autolinks',
    features: ['autolink'],
    expectedAst: ['paragraph'],
    source: '<https://example.com> <user@example.com>',
    html: '<p><a href="https://example.com">https://example.com</a> <a href="mailto:user@example.com">user@example.com</a></p>',
  },
  {
    id: 'inline-html-is-safe',
    features: ['inline-html', 'raw-html'],
    expectedAst: ['paragraph'],
    source: 'text <span title="x">ok</span>',
    html: '<p>text &lt;span title=&quot;x&quot;&gt;ok&lt;/span&gt;</p>',
  },
  {
    id: 'gfm-autolinks',
    features: ['gfm-autolink'],
    expectedAst: ['paragraph'],
    source: 'www.example.com https://example.com contact@example.com',
    html: '<p><a href="http://www.example.com">www.example.com</a> <a href="https://example.com">https://example.com</a> <a href="mailto:contact@example.com">contact@example.com</a></p>',
  },
  {
    id: 'hard-and-soft-breaks',
    features: ['hard-break', 'soft-break'],
    expectedAst: ['paragraph'],
    source: 'hard  \nbreak\nsoft',
    html: '<p>hard<br>break\nsoft</p>',
  },
  {
    id: 'aligned-table',
    features: ['table', 'table-alignment'],
    expectedAst: ['table'],
    source: '| left | center | right |\n| :--- | :---: | ---: |\n| a | b | c |',
    html: '<table><thead><tr><th align="left">left</th><th align="center">center</th><th align="right">right</th></tr></thead><tbody><tr><td align="left">a</td><td align="center">b</td><td align="right">c</td></tr></tbody></table>',
  },
  {
    id: 'table-pipes-and-inline',
    features: ['table', 'table-pipe-escape', 'composition'],
    expectedAst: ['table'],
    source: 'a | b\n--- | ---\n\\| **x** | ' + tick + 'y\\|z' + tick,
    html: '<table><thead><tr><th>a</th><th>b</th></tr></thead><tbody><tr><td>| <strong>x</strong></td><td><code>y|z</code></td></tr></tbody></table>',
  },
  {
    id: 'table-empty-cell',
    features: ['table', 'table-empty-cell'],
    expectedAst: ['table'],
    source: 'a | b | c\n--- | --- | ---\n|   | x |',
    html: '<table><thead><tr><th>a</th><th>b</th><th>c</th></tr></thead><tbody><tr><td></td><td>x</td></tr></tbody></table>',
  },
  {
    id: 'table-column-mismatch',
    features: ['table', 'table-column-mismatch'],
    expectedAst: ['table'],
    source: 'a | b\n--- | ---\nonly',
    html: '<table><thead><tr><th>a</th><th>b</th></tr></thead><tbody><tr><td>only</td></tr></tbody></table>',
  },
  {
    id: 'task-list',
    features: ['task-list'],
    expectedAst: ['list'],
    source: '- [ ] todo\n- [x] done',
    html: '<ul><li><input type="checkbox" disabled> todo</li><li><input type="checkbox" checked disabled> done</li></ul>',
  },
  {
    id: 'nested-task-list',
    features: ['task-list', 'task-nesting'],
    expectedAst: ['list'],
    source: '- [x] outer\n  - [ ] inner',
    html: '<ul><li><input type="checkbox" checked disabled> outer<ul><li><input type="checkbox" disabled> inner</li></ul></li></ul>',
  },
  {
    id: 'crlf-lines',
    features: ['crlf'],
    expectedAst: ['heading', 'paragraph'],
    source: '# title\r\n\r\nbody',
    html: '<h1>title</h1><p>body</p>',
  },
  {
    id: 'cr-lines',
    features: ['cr'],
    expectedAst: ['heading', 'paragraph'],
    source: '# title\r\rbody',
    html: '<h1>title</h1><p>body</p>',
  },
  {
    id: 'tabs-and-code',
    features: ['tab'],
    expectedAst: ['code'],
    source: '\tindented code',
    html: '<pre><code>indented code</code></pre>',
  },
  {
    id: 'unicode-text',
    features: ['unicode'],
    expectedAst: ['heading', 'paragraph'],
    source: '# 你好 🌍\n\nCafé — 東京',
    html: '<h1>你好 🌍</h1><p>Café — 東京</p>',
  },
  {
    id: 'no-trailing-newline',
    features: ['no-trailing-newline'],
    expectedAst: ['paragraph'],
    source: 'plain text',
    html: '<p>plain text</p>',
  },
  {
    id: 'malformed-markers-remain-readable',
    features: ['malformed'],
    expectedAst: ['paragraph'],
    source: '#not-heading\n[unclosed(link\n~~unclosed',
    html: '<p>#not-heading\n[unclosed(link\n~~unclosed</p>',
  },
  {
    id: 'dangerous-url-is-marked',
    features: ['dangerous-url'],
    expectedAst: ['paragraph'],
    source: '[run](javascript:alert(1))',
    html: '<p><a data-markvia-unsafe-url="true">run</a></p>',
  },
  {
    id: 'composed-document',
    features: ['composition', 'blockquote', 'list-nesting', 'table', 'delete', 'gfm-autolink'],
    expectedAst: ['blockquote'],
    source: '> - **one**\n> - ~~two~~ www.example.com\n>\n> | a | b |\n> | - | - |\n> | c | d |',
    html: '<blockquote><ul><li><strong>one</strong></li><li><del>two</del> <a href="http://www.example.com">www.example.com</a></li></ul><table><thead><tr><th>a</th><th>b</th></tr></thead><tbody><tr><td>c</td><td>d</td></tr></tbody></table></blockquote>',
  },
] as const
